name: Setup

runs:
  using: composite
  steps:
    - name: Install postgres client
      shell: bash
      run: |
        sudo apt-get -yqq install libpq-dev

    - name: Install GIS packages
      shell: bash
      run: |
        sudo apt-get -yqq install libgeos-dev libproj-dev gdal-bin

    - name: Install gems
      shell: bash
      run: |
        gem install bundler -v 2.3.5
        bundle config set --local path 'vendor/bundle'
        bundle install --jobs 4 --retry 3

    - name: Setup database
      shell: bash
      env:
        DATABASE_URL: postgis://postgres:postgres@localhost:5432/wpets_test
        RAILS_ENV: test
      run: |
        bundle exec rake db:setup
