class CleanupCountryColumns < ActiveRecord::Migration
  def up
    execute "UPDATE signatures SET location_code = 'AF' WHERE country = 'Afghanistan'"
    execute "UPDATE signatures SET location_code = 'AL' WHERE country = 'Albania'"
    execute "UPDATE signatures SET location_code = 'DZ' WHERE country = 'Algeria'"
    execute "UPDATE signatures SET location_code = 'AS' WHERE country = 'American Samoa'"
    execute "UPDATE signatures SET location_code = 'AD' WHERE country = 'Andorra'"
    execute "UPDATE signatures SET location_code = 'AO' WHERE country = 'Angola'"
    execute "UPDATE signatures SET location_code = 'AI' WHERE country = 'Anguilla (British Overseas Territory)'"
    execute "UPDATE signatures SET location_code = 'AG' WHERE country = 'Antigua and Barbuda'"
    execute "UPDATE signatures SET location_code = 'AR' WHERE country = 'Argentina'"
    execute "UPDATE signatures SET location_code = 'AM' WHERE country = 'Armenia'"
    execute "UPDATE signatures SET location_code = 'AW' WHERE country = 'Aruba/Dutch Caribbean'"
    execute "UPDATE signatures SET location_code = 'SH' WHERE country = 'Ascension Island (British Overseas Territory)'"
    execute "UPDATE signatures SET location_code = 'AU' WHERE country = 'Australia'"
    execute "UPDATE signatures SET location_code = 'AT' WHERE country = 'Austria'"
    execute "UPDATE signatures SET location_code = 'AZ' WHERE country = 'Azerbaijan'"
    execute "UPDATE signatures SET location_code = 'BS' WHERE country = 'Bahamas'"
    execute "UPDATE signatures SET location_code = 'BH' WHERE country = 'Bahrain'"
    execute "UPDATE signatures SET location_code = 'BD' WHERE country = 'Bangladesh'"
    execute "UPDATE signatures SET location_code = 'BB' WHERE country = 'Barbados'"
    execute "UPDATE signatures SET location_code = 'BY' WHERE country = 'Belarus'"
    execute "UPDATE signatures SET location_code = 'BE' WHERE country = 'Belgium'"
    execute "UPDATE signatures SET location_code = 'BZ' WHERE country = 'Belize'"
    execute "UPDATE signatures SET location_code = 'BJ' WHERE country = 'Benin'"
    execute "UPDATE signatures SET location_code = 'BM' WHERE country = 'Bermuda (British Overseas Territory)'"
    execute "UPDATE signatures SET location_code = 'BT' WHERE country = 'Bhutan'"
    execute "UPDATE signatures SET location_code = 'BO' WHERE country = 'Bolivia'"
    execute "UPDATE signatures SET location_code = 'BA' WHERE country = 'Bosnia and Herzegovina'"
    execute "UPDATE signatures SET location_code = 'BW' WHERE country = 'Botswana'"
    execute "UPDATE signatures SET location_code = 'BR' WHERE country = 'Brazil'"
    execute "UPDATE signatures SET location_code = 'BAT' WHERE country = 'British Antarctic Territory'"
    execute "UPDATE signatures SET location_code = 'IO' WHERE country = 'British Indian Ocean Territory'"
    execute "UPDATE signatures SET location_code = 'VG' WHERE country = 'British Virgin Islands (British Overseas Territory)'"
    execute "UPDATE signatures SET location_code = 'BN' WHERE country = 'Brunei'"
    execute "UPDATE signatures SET location_code = 'BG' WHERE country = 'Bulgaria'"
    execute "UPDATE signatures SET location_code = 'BF' WHERE country = 'Burkina Faso'"
    execute "UPDATE signatures SET location_code = 'MM' WHERE country = 'Burma'"
    execute "UPDATE signatures SET location_code = 'BI' WHERE country = 'Burundi'"
    execute "UPDATE signatures SET location_code = 'KH' WHERE country = 'Cambodia'"
    execute "UPDATE signatures SET location_code = 'CM' WHERE country = 'Cameroon'"
    execute "UPDATE signatures SET location_code = 'CA' WHERE country = 'Canada'"
    execute "UPDATE signatures SET location_code = 'CV' WHERE country = 'Cape Verde'"
    execute "UPDATE signatures SET location_code = 'KY' WHERE country = 'Cayman Islands'"
    execute "UPDATE signatures SET location_code = 'CF' WHERE country = 'Central African Republic'"
    execute "UPDATE signatures SET location_code = 'TD' WHERE country = 'Chad'"
    execute "UPDATE signatures SET location_code = NULL WHERE country = 'Channel Islands'"
    execute "UPDATE signatures SET location_code = 'CL' WHERE country = 'Chile'"
    execute "UPDATE signatures SET location_code = 'CN' WHERE country = 'China'"
    execute "UPDATE signatures SET location_code = 'CO' WHERE country = 'Colombia'"
    execute "UPDATE signatures SET location_code = 'KM' WHERE country = 'Comoros'"
    execute "UPDATE signatures SET location_code = 'CG' WHERE country = 'Congo'"
    execute "UPDATE signatures SET location_code = 'CD' WHERE country = 'Congo (Democratic Republic)'"
    execute "UPDATE signatures SET location_code = 'CR' WHERE country = 'Costa Rica'"
    execute "UPDATE signatures SET location_code = 'HR' WHERE country = 'Croatia'"
    execute "UPDATE signatures SET location_code = 'CU' WHERE country = 'Cuba'"
    execute "UPDATE signatures SET location_code = 'CY' WHERE country = 'Cyprus'"
    execute "UPDATE signatures SET location_code = 'CZ' WHERE country = 'Czech Republic'"
    execute "UPDATE signatures SET location_code = 'DK' WHERE country = 'Denmark'"
    execute "UPDATE signatures SET location_code = 'DJ' WHERE country = 'Djibouti'"
    execute "UPDATE signatures SET location_code = 'DM' WHERE country = 'Dominica, Commonwealth of'"
    execute "UPDATE signatures SET location_code = 'DO' WHERE country = 'Dominican Republic'"
    execute "UPDATE signatures SET location_code = 'TL' WHERE country = 'East Timor (Timor-Leste)'"
    execute "UPDATE signatures SET location_code = 'EC' WHERE country = 'Ecuador'"
    execute "UPDATE signatures SET location_code = 'EG' WHERE country = 'Egypt'"
    execute "UPDATE signatures SET location_code = 'SV' WHERE country = 'El Salvador'"
    execute "UPDATE signatures SET location_code = 'GQ' WHERE country = 'Equatorial Guinea'"
    execute "UPDATE signatures SET location_code = 'ER' WHERE country = 'Eritrea'"
    execute "UPDATE signatures SET location_code = 'EE' WHERE country = 'Estonia'"
    execute "UPDATE signatures SET location_code = 'ET' WHERE country = 'Ethiopia'"
    execute "UPDATE signatures SET location_code = 'FK' WHERE country = 'Falkland Islands (British Overseas Territory)'"
    execute "UPDATE signatures SET location_code = 'FJ' WHERE country = 'Fiji'"
    execute "UPDATE signatures SET location_code = 'FI' WHERE country = 'Finland'"
    execute "UPDATE signatures SET location_code = 'FR' WHERE country = 'France'"
    execute "UPDATE signatures SET location_code = 'GF' WHERE country = 'French Guiana'"
    execute "UPDATE signatures SET location_code = 'PF' WHERE country = 'French Polynesia'"
    execute "UPDATE signatures SET location_code = 'GA' WHERE country = 'Gabon'"
    execute "UPDATE signatures SET location_code = 'GM' WHERE country = 'Gambia'"
    execute "UPDATE signatures SET location_code = 'GE' WHERE country = 'Georgia'"
    execute "UPDATE signatures SET location_code = 'DE' WHERE country = 'Germany'"
    execute "UPDATE signatures SET location_code = 'GH' WHERE country = 'Ghana'"
    execute "UPDATE signatures SET location_code = 'GI' WHERE country = 'Gibraltar'"
    execute "UPDATE signatures SET location_code = 'GR' WHERE country = 'Greece'"
    execute "UPDATE signatures SET location_code = 'GD' WHERE country = 'Grenada'"
    execute "UPDATE signatures SET location_code = 'GP' WHERE country = 'Guadeloupe'"
    execute "UPDATE signatures SET location_code = 'GT' WHERE country = 'Guatemala'"
    execute "UPDATE signatures SET location_code = 'GN' WHERE country = 'Guinea'"
    execute "UPDATE signatures SET location_code = 'GW' WHERE country = 'Guinea-Bissau'"
    execute "UPDATE signatures SET location_code = 'GY' WHERE country = 'Guyana'"
    execute "UPDATE signatures SET location_code = 'HT' WHERE country = 'Haiti'"
    execute "UPDATE signatures SET location_code = 'HN' WHERE country = 'Honduras'"
    execute "UPDATE signatures SET location_code = 'HK' WHERE country = 'Hong Kong'"
    execute "UPDATE signatures SET location_code = 'HU' WHERE country = 'Hungary'"
    execute "UPDATE signatures SET location_code = 'IS' WHERE country = 'Iceland'"
    execute "UPDATE signatures SET location_code = 'IN' WHERE country = 'India'"
    execute "UPDATE signatures SET location_code = 'ID' WHERE country = 'Indonesia'"
    execute "UPDATE signatures SET location_code = 'IR' WHERE country = 'Iran'"
    execute "UPDATE signatures SET location_code = 'IQ' WHERE country = 'Iraq'"
    execute "UPDATE signatures SET location_code = 'IE' WHERE country = 'Ireland'"
    execute "UPDATE signatures SET location_code = 'IM' WHERE country = 'Isle of Man'"
    execute "UPDATE signatures SET location_code = 'IL' WHERE country = 'Israel'"
    execute "UPDATE signatures SET location_code = 'IT' WHERE country = 'Italy'"
    execute "UPDATE signatures SET location_code = 'CI' WHERE country = 'Ivory Coast (Cote d''Ivoire)'"
    execute "UPDATE signatures SET location_code = 'JM' WHERE country = 'Jamaica'"
    execute "UPDATE signatures SET location_code = 'JP' WHERE country = 'Japan'"
    execute "UPDATE signatures SET location_code = 'JO' WHERE country = 'Jordan'"
    execute "UPDATE signatures SET location_code = 'KZ' WHERE country = 'Kazakhstan'"
    execute "UPDATE signatures SET location_code = 'KE' WHERE country = 'Kenya'"
    execute "UPDATE signatures SET location_code = 'KI' WHERE country = 'Kiribati'"
    execute "UPDATE signatures SET location_code = 'KP' WHERE country = 'North Korea'"
    execute "UPDATE signatures SET location_code = 'KR' WHERE country = 'South Korea'"
    execute "UPDATE signatures SET location_code = 'XK' WHERE country = 'Kosovo'"
    execute "UPDATE signatures SET location_code = 'KW' WHERE country = 'Kuwait'"
    execute "UPDATE signatures SET location_code = 'KG' WHERE country = 'Kyrgyzstan'"
    execute "UPDATE signatures SET location_code = 'LA' WHERE country = 'Laos'"
    execute "UPDATE signatures SET location_code = 'LV' WHERE country = 'Latvia'"
    execute "UPDATE signatures SET location_code = 'LB' WHERE country = 'Lebanon'"
    execute "UPDATE signatures SET location_code = 'LS' WHERE country = 'Lesotho'"
    execute "UPDATE signatures SET location_code = 'LR' WHERE country = 'Liberia'"
    execute "UPDATE signatures SET location_code = 'LY' WHERE country = 'Libya'"
    execute "UPDATE signatures SET location_code = 'LI' WHERE country = 'Liechtenstein'"
    execute "UPDATE signatures SET location_code = 'LT' WHERE country = 'Lithuania'"
    execute "UPDATE signatures SET location_code = 'LU' WHERE country = 'Luxembourg'"
    execute "UPDATE signatures SET location_code = 'MO' WHERE country = 'Macao'"
    execute "UPDATE signatures SET location_code = 'MK' WHERE country = 'Macedonia'"
    execute "UPDATE signatures SET location_code = 'MG' WHERE country = 'Madagascar'"
    execute "UPDATE signatures SET location_code = 'MW' WHERE country = 'Malawi'"
    execute "UPDATE signatures SET location_code = 'MY' WHERE country = 'Malaysia'"
    execute "UPDATE signatures SET location_code = 'MV' WHERE country = 'Maldives'"
    execute "UPDATE signatures SET location_code = 'ML' WHERE country = 'Mali'"
    execute "UPDATE signatures SET location_code = 'MT' WHERE country = 'Malta'"
    execute "UPDATE signatures SET location_code = 'MH' WHERE country = 'Marshall Islands'"
    execute "UPDATE signatures SET location_code = 'MQ' WHERE country = 'Martinique'"
    execute "UPDATE signatures SET location_code = 'MR' WHERE country = 'Mauritania'"
    execute "UPDATE signatures SET location_code = 'MU' WHERE country = 'Mauritius'"
    execute "UPDATE signatures SET location_code = 'YT' WHERE country = 'Mayotte'"
    execute "UPDATE signatures SET location_code = 'MX' WHERE country = 'Mexico'"
    execute "UPDATE signatures SET location_code = 'FM' WHERE country = 'Micronesia'"
    execute "UPDATE signatures SET location_code = 'MD' WHERE country = 'Moldova'"
    execute "UPDATE signatures SET location_code = 'MC' WHERE country = 'Monaco'"
    execute "UPDATE signatures SET location_code = 'MN' WHERE country = 'Mongolia'"
    execute "UPDATE signatures SET location_code = 'ME' WHERE country = 'Montenegro'"
    execute "UPDATE signatures SET location_code = 'MS' WHERE country = 'Montserrat (British Overseas Territory)'"
    execute "UPDATE signatures SET location_code = 'MA' WHERE country = 'Morocco'"
    execute "UPDATE signatures SET location_code = 'MZ' WHERE country = 'Mozambique'"
    execute "UPDATE signatures SET location_code = 'NA' WHERE country = 'Namibia'"
    execute "UPDATE signatures SET location_code = 'NR' WHERE country = 'Nauru'"
    execute "UPDATE signatures SET location_code = 'NP' WHERE country = 'Nepal'"
    execute "UPDATE signatures SET location_code = 'NL' WHERE country = 'Netherlands'"
    execute "UPDATE signatures SET location_code = 'NC' WHERE country = 'New Caledonia'"
    execute "UPDATE signatures SET location_code = 'NZ' WHERE country = 'New Zealand'"
    execute "UPDATE signatures SET location_code = 'NI' WHERE country = 'Nicaragua'"
    execute "UPDATE signatures SET location_code = 'NE' WHERE country = 'Niger'"
    execute "UPDATE signatures SET location_code = 'NG' WHERE country = 'Nigeria'"
    execute "UPDATE signatures SET location_code = 'NO' WHERE country = 'Norway'"
    execute "UPDATE signatures SET location_code = 'OM' WHERE country = 'Oman'"
    execute "UPDATE signatures SET location_code = 'PK' WHERE country = 'Pakistan'"
    execute "UPDATE signatures SET location_code = 'PW' WHERE country = 'Palau'"
    execute "UPDATE signatures SET location_code = 'PS' WHERE country = 'The Occupied Palestinian Territories'"
    execute "UPDATE signatures SET location_code = 'PA' WHERE country = 'Panama'"
    execute "UPDATE signatures SET location_code = 'PG' WHERE country = 'Papua New Guinea'"
    execute "UPDATE signatures SET location_code = 'PY' WHERE country = 'Paraguay'"
    execute "UPDATE signatures SET location_code = 'PE' WHERE country = 'Peru'"
    execute "UPDATE signatures SET location_code = 'PH' WHERE country = 'Philippines'"
    execute "UPDATE signatures SET location_code = 'PN' WHERE country = 'Pitcairn'"
    execute "UPDATE signatures SET location_code = 'PL' WHERE country = 'Poland'"
    execute "UPDATE signatures SET location_code = 'PT' WHERE country = 'Portugal'"
    execute "UPDATE signatures SET location_code = 'QA' WHERE country = 'Qatar'"
    execute "UPDATE signatures SET location_code = 'RE' WHERE country = 'Réunion'"
    execute "UPDATE signatures SET location_code = 'RO' WHERE country = 'Romania'"
    execute "UPDATE signatures SET location_code = 'RU' WHERE country = 'Russian Federation'"
    execute "UPDATE signatures SET location_code = 'RW' WHERE country = 'Rwanda'"
    execute "UPDATE signatures SET location_code = 'SH' WHERE country = 'St Helena'"
    execute "UPDATE signatures SET location_code = 'KN' WHERE country = 'St Kitts and Nevis'"
    execute "UPDATE signatures SET location_code = 'LC' WHERE country = 'St Lucia'"
    execute "UPDATE signatures SET location_code = 'PM' WHERE country = 'St Pierre & Miquelon'"
    execute "UPDATE signatures SET location_code = 'VC' WHERE country = 'St Vincent and the Grenadines'"
    execute "UPDATE signatures SET location_code = 'WS' WHERE country = 'Samoa'"
    execute "UPDATE signatures SET location_code = 'ST' WHERE country = 'São Tomé and Principe'"
    execute "UPDATE signatures SET location_code = 'SA' WHERE country = 'Saudi Arabia'"
    execute "UPDATE signatures SET location_code = 'SN' WHERE country = 'Senegal'"
    execute "UPDATE signatures SET location_code = 'RS' WHERE country = 'Serbia'"
    execute "UPDATE signatures SET location_code = 'SC' WHERE country = 'Seychelles'"
    execute "UPDATE signatures SET location_code = 'SL' WHERE country = 'Sierra Leone'"
    execute "UPDATE signatures SET location_code = 'SG' WHERE country = 'Singapore'"
    execute "UPDATE signatures SET location_code = 'SK' WHERE country = 'Slovakia'"
    execute "UPDATE signatures SET location_code = 'SI' WHERE country = 'Slovenia'"
    execute "UPDATE signatures SET location_code = 'SB' WHERE country = 'Solomon Islands'"
    execute "UPDATE signatures SET location_code = 'SO' WHERE country = 'Somalia'"
    execute "UPDATE signatures SET location_code = 'ZA' WHERE country = 'South Africa'"
    execute "UPDATE signatures SET location_code = 'GS' WHERE country = 'South Georgia & South Sandwich Islands'"
    execute "UPDATE signatures SET location_code = 'ES' WHERE country = 'Spain'"
    execute "UPDATE signatures SET location_code = 'LK' WHERE country = 'Sri Lanka'"
    execute "UPDATE signatures SET location_code = 'SD' WHERE country = 'Sudan'"
    execute "UPDATE signatures SET location_code = 'SR' WHERE country = 'Suriname'"
    execute "UPDATE signatures SET location_code = 'SZ' WHERE country = 'Swaziland'"
    execute "UPDATE signatures SET location_code = 'SE' WHERE country = 'Sweden'"
    execute "UPDATE signatures SET location_code = 'CH' WHERE country = 'Switzerland'"
    execute "UPDATE signatures SET location_code = 'SY' WHERE country = 'Syria'"
    execute "UPDATE signatures SET location_code = 'TW' WHERE country = 'Taiwan'"
    execute "UPDATE signatures SET location_code = 'TJ' WHERE country = 'Tajikistan'"
    execute "UPDATE signatures SET location_code = 'TZ' WHERE country = 'Tanzania'"
    execute "UPDATE signatures SET location_code = 'TH' WHERE country = 'Thailand'"
    execute "UPDATE signatures SET location_code = 'TG' WHERE country = 'Togo'"
    execute "UPDATE signatures SET location_code = 'TO' WHERE country = 'Tonga'"
    execute "UPDATE signatures SET location_code = 'TT' WHERE country = 'Trinidad and Tobago'"
    execute "UPDATE signatures SET location_code = 'SH' WHERE country = 'Tristan da Cunha'"
    execute "UPDATE signatures SET location_code = 'TN' WHERE country = 'Tunisia'"
    execute "UPDATE signatures SET location_code = 'TR' WHERE country = 'Turkey'"
    execute "UPDATE signatures SET location_code = 'TM' WHERE country = 'Turkmenistan'"
    execute "UPDATE signatures SET location_code = 'TC' WHERE country = 'Turks & Caicos Islands (British Overseas Territory)'"
    execute "UPDATE signatures SET location_code = 'TV' WHERE country = 'Tuvalu'"
    execute "UPDATE signatures SET location_code = 'UG' WHERE country = 'Uganda'"
    execute "UPDATE signatures SET location_code = 'UA' WHERE country = 'Ukraine'"
    execute "UPDATE signatures SET location_code = 'AE' WHERE country = 'United Arab Emirates'"
    execute "UPDATE signatures SET location_code = 'GB' WHERE country = 'United Kingdom'"
    execute "UPDATE signatures SET location_code = 'US' WHERE country = 'United States'"
    execute "UPDATE signatures SET location_code = 'UY' WHERE country = 'Uruguay'"
    execute "UPDATE signatures SET location_code = 'UZ' WHERE country = 'Uzbekistan'"
    execute "UPDATE signatures SET location_code = 'VU' WHERE country = 'Vanuatu'"
    execute "UPDATE signatures SET location_code = 'VE' WHERE country = 'Venezuela'"
    execute "UPDATE signatures SET location_code = 'VN' WHERE country = 'Vietnam'"
    execute "UPDATE signatures SET location_code = 'WF' WHERE country = 'Wallis & Futuna'"
    execute "UPDATE signatures SET location_code = 'EH' WHERE country = 'Western Sahara'"
    execute "UPDATE signatures SET location_code = 'YE' WHERE country = 'Yemen'"
    execute "UPDATE signatures SET location_code = 'ZM' WHERE country = 'Zambia'"
    execute "UPDATE signatures SET location_code = 'ZW' WHERE country = 'Zimbabwe'"

    remove_column :country_petition_journals, :country
    remove_column :signatures, :country

    execute "TRUNCATE TABLE country_petition_journals"

    execute <<-SQL
      INSERT INTO country_petition_journals
        (petition_id, location_code, signature_count, created_at, updated_at)
      SELECT
        petition_id, location_code, COUNT(*) AS signature_count,
        timezone('utc', now()), timezone('utc', now())
      FROM signatures
      WHERE state = 'validated'
      AND location_code <> ''
      GROUP BY petition_id, location_code
    SQL
  end

  def down
    raise ActiveRecord::IrreversibleMigration
  end
end
